# vbtc.github.io configuration

title: VBTC Blog
author: Thong Ngo
email: quangthong1011@gmail.com
description: News and announcements regarding VBTC, the first Bitcoin live exchange in Vietnam
baseurl: https://vbtc.exchange
url: "https://vbtc.github.io"
show_excerpts: true

twitter_username: vbtc_vietnam
facebook_username: VBTC.vn
github_username: vbtc
rss: feed.xml

google_analytics: UA-134715319-1

permalink: /:year/:categories/:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
